ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recipes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recipe_components" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cutting_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_logs" ENABLE ROW LEVEL SECURITY;